
/* Includes added by #pragma extra_include */
#include "vector"
/********************************************************************
* RootDictionary.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error RootDictionary.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableRootDictionary();
extern void G__cpp_setup_inheritanceRootDictionary();
extern void G__cpp_setup_typetableRootDictionary();
extern void G__cpp_setup_memvarRootDictionary();
extern void G__cpp_setup_globalRootDictionary();
extern void G__cpp_setup_memfuncRootDictionary();
extern void G__cpp_setup_funcRootDictionary();
extern void G__set_cpp_environmentRootDictionary();
}


#include "TObject.h"
#include "TMemberInspector.h"

#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__RootDictionaryLN_vectorlElongcOallocatorlElonggRsPgR;
extern G__linked_taginfo G__RootDictionaryLN_vectorlElongcOallocatorlElonggRsPgRcLcLiterator;
extern G__linked_taginfo G__RootDictionaryLN_reverse_iteratorlEvectorlElongcOallocatorlElonggRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RootDictionaryLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__RootDictionaryLN_vectorlEfloatcOallocatorlEfloatgRsPgRcLcLiterator;
extern G__linked_taginfo G__RootDictionaryLN_reverse_iteratorlEvectorlEfloatcOallocatorlEfloatgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RootDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__RootDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<long,allocator<long> > G__vectorlElongcOallocatorlElonggRsPgR;
typedef vector<float,allocator<float> > G__vectorlEfloatcOallocatorlEfloatgRsPgR;
